apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    name: kvm-device-plugin
  name: kvm-device-plugin
spec:
  selector:
    matchLabels:
      name: kvm-device-plugin
  template:
    metadata:
      labels:
        name: kvm-device-plugin
    spec:
      serviceAccountName: kvm-device-plugin
      containers:
      - name: kvm-device-plugin
        image: registry.svc.ci.openshift.org/cgwalters/kvm-device-plugin
        securityContext:
          privileged: true
        volumeMounts:
          - name: device-plugin
            mountPath: /var/lib/kubelet/device-plugins
      volumes:
        - name: device-plugin
          hostPath:
            path: /var/lib/kubelet/device-plugins
